INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  1,	'Bulbasaur',    '001',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  2,	'Ivysaur',      '002',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  3,	'Venusaur',     '003',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  4,	'Charmander',   '004',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  5,	'Charmeleon',   '005',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  6,	'Charizard',    '006',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  7,	'Squirtle',     '007',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  8,	'Wartortle',    '008',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (  9,	'Blastoise',    '009',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 10,	'Caterpie',     '010',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 11,	'Metapod',      '011',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 12, 	'Butterfree',   '012',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 13,	'Weedle',       '013',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 14,	'Kakuna',       '014',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 15,	'Beedrill',     '015',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 16,	'Pidgey',       '016',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 17,	'Pidgeotto',    '017',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 18,	'Pidgeot',      '018',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 19,	'Rattata',      '019',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 20,	'Raticate',     '020',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 21,	'Spearow',      '021',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 22,	'Fearow',       '022',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 23,	'Ekans',        '023',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 24,	'Arbok',        '024',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 25,	'Pikachu',      '025',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 26,	'Raichu',       '026',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 27,	'Sandshrew',    '027',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 28,	'Sandslash',    '028',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 29,	'Nidoran♀',     '029',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 30,	'Nidorina',     '030',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 31,	'Nidoqueen',    '031',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 32,	'Nidoran♂',     '032',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 33,	'Nidorino',     '033',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 34,	'Nidoking',     '034',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 35,	'Clefairy',     '035',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 36,	'Clefable',     '036',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 37,	'Vulpix',       '037',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 38,	'Ninetales',    '038',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 39,	'Jigglypuff',   '039',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 40,	'Wigglytuff',   '040',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 41,	'Zubat',        '041',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 42,	'Golbat',       '042',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 43,	'Oddish',       '043',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 44,	'Gloom',        '044',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 45,	'Vileplume',    '045',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 46,	'Paras',        '046',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 47,	'Parasect',     '047',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 48,	'Venonat',      '048',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 49,	'Venomoth',     '049',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 50,	'Diglett',      '050',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 51,	'Dugtrio',      '051',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 52,	'Meowth',       '052',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 53,	'Persian',      '053',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 54,	'Psyduck',      '054',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 55,	'Golduck',      '055',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 56,	'Mankey',       '056',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 57,	'Primeape',     '057',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 58,	'Growlithe',    '058',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 59,	'Arcanine',     '059',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 60,	'Poliwag',      '060',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 61,	'Poliwhirl',    '061',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 62,	'Poliwrath',    '062',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 63,	'Abra',         '063',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 64,	'Kadabra',      '064',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 65,	'Alakazam',     '065',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 66,	'Machop',       '066',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 67,	'Machoke',      '067',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 68,	'Machamp',      '068',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 69,	'Bellsprout',   '069',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 70,	'Weepinbell',   '070',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 71,	'Victreebel',   '071',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 72,	'Tentacool',    '072',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 73,	'Tentacruel',   '073',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 74,	'Geodude',      '074',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 75,	'Graveler',     '075',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 76,	'Golem',        '076',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 77,	'Ponyta',       '077',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 78,	'Rapidash',     '078',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 79,	'Slowpoke',     '079',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 80,	'Slowbro',      '080',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 81,	'Magnemite',    '081',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 82,	'Magneton',     '082',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 83,	'Farfetch\'d',  '083',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 84,	'Doduo',        '084',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 85,	'Dodrio',       '085',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 86,	'Seel',         '086',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 87,	'Dewgong',      '087',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 88,	'Grimer',       '088',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 89,	'Muk',          '089',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 90,	'Shellder',     '090',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 91,	'Cloyster',     '091',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 92,	'Gastly',       '092',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 93,	'Haunter',      '093',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 94,	'Gengar',       '094',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 95,	'Onix',         '095',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 96,	'Drowzee',      '096',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 97,	'Hypno',        '097',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 98,	'Krabby',       '098',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 99,	'Kingler',      '099',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (100,    'Voltorb',      '100',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (101,   	'Electrode',    '101',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (102,	'Exeggcute',    '102',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (103,	'Exeggutor',    '103',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (104,	'Cubone',       '104',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (105,	'Marowak',      '105',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (106,	'Hitmonlee',    '106',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (107,	'Hitmonchan',   '107',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (108,	'Lickitung',    '108',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (109,	'Koffing',      '109',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (110,	'Weezing',      '110',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (111,	'Rhyhorn',      '111',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (112,	'Rhydon',       '112',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (113,	'Chansey',      '113',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (114,	'Tangela',      '114',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (115,	'Kangaskhan',   '115',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (116,	'Horsea',       '116',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (117,	'Seadra',       '117',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (118,	'Goldeen',      '118',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (119,	'Seaking',      '119',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (120,	'Staryu',       '120',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (121,	'Starmie',      '121',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (122,	'Mr._Mime',     '122',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (123,	'Scyther',      '123',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (124,	'Jynx',         '124',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (125,	'Electabuzz',   '125',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (126,	'Magmar',       '126',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (127,	'Pinsir',       '127',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (128,	'Tauros',       '128',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (129,	'Magikarp',     '129',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (130,	'Gyarados',     '130',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (131,	'Lapras',       '131',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (132,	'Ditto',        '132',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (133,	'Eevee',        '133',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (134,	'Vaporeon',     '134',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (135,	'Jolteon',      '135',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (136,	'Flareon',      '136',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (137,	'Porygon',      '137',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (138,	'Omanyte',      '138',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (139,	'Omastar',      '139',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (140,	'Kabuto',       '140',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (141,	'Kabutops',     '141',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (142,	'Aerodactyl',   '142',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (143,	'Snorlax',      '143',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (144,	'Articuno',     '144',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (145,	'Zapdos',       '145',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (146,	'Moltres',      '146',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (147,	'Dratini',      '147',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (148,	'Dragonair',    '148',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (149,	'Dragonite',    '149',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (150,	'Mewtwo',       '150',	  '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (151,	'Mew',          '151',	  '1ª Geração');