INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 1,	 	'Bulbasaur',    '001',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 2,	 	'Ivysaur',      '002',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 3,	 	'Venusaur',     '003',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 4,	 	'Charmander',   '004',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 5,	 	'Charmeleon',   '005',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 6,	 	'Charizard',    '006',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 7,	 	'Squirtle',     '007',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 8,	 	'Wartortle',    '008',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES ( 9,	 	'Blastoise',    '009',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (10,	 	'Caterpie',     '010',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (11,		'Metapod',      '011',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (12, 	'Butterfree',   '012',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (13,		'Weedle',       '013',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (14,		'Kakuna',       '014',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (15,		'Beedrill',     '015',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (16,		'Pidgey',       '016',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (17,		'Pidgeotto',    '017',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (18,		'Pidgeot',      '018',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (19,		'Rattata',      '019',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (20,		'Raticate',     '020',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (21,		'Spearow',      '021',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (22,		'Fearow',       '022',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (23,		'Ekans',        '023',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (24,		'Arbok',        '024',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (25,		'Pikachu',      '025',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (26,		'Raichu',       '026',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (27,		'Sandshrew',    '027',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (28,		'Sandslash',    '028',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (29,		'Nidoran♀',     '029',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (30,		'Nidorina',     '030',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (31,		'Nidoqueen',    '031',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (32,		'Nidoran♂',     '032',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (33,		'Nidorino',     '033',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (34,		'Nidoking',     '034',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (35,		'Clefairy',     '035',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (36,		'Clefable',     '036',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (37,		'Vulpix',       '037',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (38,		'Ninetales',    '038',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (39,		'Jigglypuff',   '039',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (40,		'Wigglytuff',   '040',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (41,		'Zubat',        '041',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (42,		'Golbat',       '042',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (43,		'Oddish',       '043',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (44,		'Gloom',        '044',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (45,		'Vileplume',    '045',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (46,		'Paras',        '046',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (47,		'Parasect',     '047',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (48,		'Venonat',      '048',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (49,		'Venomoth',     '049',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (50,		'Diglett',      '050',    '1ª Geração');
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao`) VALUES (51,		'Dugtrio',      '051',	  '1ª Geração');