INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 1, 10);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 1, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 2, 10);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 2, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 3, 10);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 3, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 4, 7);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 5, 7);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 6, 7);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 6, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 7, 18);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 8, 18);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES ( 9, 18);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (10, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (11, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (12, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (12, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (13, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (13, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (14, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (14, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (15, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (15, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (16, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (16, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (17, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (17, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (18, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (18, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (19, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (20, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (21, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (21, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (22, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (22, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (23, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (24, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (25, 4);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (26, 4);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (27, 11);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (28, 11);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (29, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (30, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (31, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (31, 11);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (32, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (33, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (34, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (34, 11);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (35, 5);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (36, 5);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (37, 7);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (38, 7);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (39, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (39, 5);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (40, 13);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (40, 5);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (41, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (41, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (42, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (42, 8);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (43, 10);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (43, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (44, 10);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (44, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (45, 10);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (45, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (46, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (46, 10);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (47, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (47, 10);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (48, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (48, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (49, 1);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (49, 14);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (50, 11);
INSERT INTO pokemon_tipo (`id_pokemon`, `id_tipo`) VALUES (51, 11);