INSERT INTO geracao(id, nome, regiao) VALUES(1, '1ª Geração', 'Kanto');
INSERT INTO geracao(id, nome, regiao) VALUES(2, '2ª Geração', 'Johto');
INSERT INTO geracao(id, nome, regiao) VALUES(3, '3ª Geração', 'Hoenn');
INSERT INTO geracao(id, nome, regiao) VALUES(4, '4ª Geração', 'Sinnoh');
INSERT INTO geracao(id, nome, regiao) VALUES(5, '5ª Geração', 'Unova');
INSERT INTO geracao(id, nome, regiao) VALUES(6, '6ª Geração', 'Kalos');
INSERT INTO geracao(id, nome, regiao) VALUES(7, '7ª Geração', 'Alola');
INSERT INTO geracao(id, nome, regiao) VALUES(8, '8ª Geração', 'Galar');
--INSERT INTO geracao(id, nome, regiao) VALUES(9, '7ª Geração', 'Formas de Alola');
--INSERT INTO geracao(id, nome, regiao) VALUES(10, '8ª Geração', 'Formas de Galar');