INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  1,	'Bulbasaur',    '001', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  2,	'Ivysaur',      '002', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  3,	'Venusaur',     '003', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  4,	'Charmander',   '004', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  5,	'Charmeleon',   '005', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  6,	'Charizard',    '006', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  7,	'Squirtle',     '007', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  8,	'Wartortle',    '008', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (  9,	'Blastoise',    '009', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 10,	'Caterpie',     '010', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 11,	'Metapod',      '011', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 12, 'Butterfree',   '012', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 13,	'Weedle',       '013', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 14,	'Kakuna',       '014', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 15,	'Beedrill',     '015', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 16,	'Pidgey',       '016', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 17,	'Pidgeotto',    '017', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 18,	'Pidgeot',      '018', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 19,	'Rattata',      '019', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 20,	'Raticate',     '020', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 21,	'Spearow',      '021', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 22,	'Fearow',       '022', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 23,	'Ekans',        '023', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 24,	'Arbok',        '024', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 25,	'Pikachu',      '025', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 26,	'Raichu',       '026', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 27,	'Sandshrew',    '027', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 28,	'Sandslash',    '028', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 29,	'Nidoran♀',     '029', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 30,	'Nidorina',     '030', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 31,	'Nidoqueen',    '031', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 32,	'Nidoran♂',     '032', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 33,	'Nidorino',     '033', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 34,	'Nidoking',     '034', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 35,	'Clefairy',     '035', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 36,	'Clefable',     '036', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 37,	'Vulpix',       '037', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 38,	'Ninetales',    '038', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 39,	'Jigglypuff',   '039', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 40,	'Wigglytuff',   '040', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 41,	'Zubat',        '041', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 42,	'Golbat',       '042', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 43,	'Oddish',       '043', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 44,	'Gloom',        '044', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 45,	'Vileplume',    '045', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 46,	'Paras',        '046', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 47,	'Parasect',     '047', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 48,	'Venonat',      '048', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 49,	'Venomoth',     '049', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 50,	'Diglett',      '050', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 51,	'Dugtrio',      '051', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 52,	'Meowth',       '052', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 53,	'Persian',      '053', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 54,	'Psyduck',      '054', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 55,	'Golduck',      '055', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 56,	'Mankey',       '056', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 57,	'Primeape',     '057', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 58,	'Growlithe',    '058', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 59,	'Arcanine',     '059', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 60,	'Poliwag',      '060', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 61,	'Poliwhirl',    '061', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 62,	'Poliwrath',    '062', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 63,	'Abra',         '063', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 64,	'Kadabra',      '064', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 65,	'Alakazam',     '065', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 66,	'Machop',       '066', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 67,	'Machoke',      '067', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 68,	'Machamp',      '068', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 69,	'Bellsprout',   '069', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 70,	'Weepinbell',   '070', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 71,	'Victreebel',   '071', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 72,	'Tentacool',    '072', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 73,	'Tentacruel',   '073', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 74,	'Geodude',      '074', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 75,	'Graveler',     '075', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 76,	'Golem',        '076', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 77,	'Ponyta',       '077', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 78,	'Rapidash',     '078', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 79,	'Slowpoke',     '079', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 80,	'Slowbro',      '080', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 81,	'Magnemite',    '081', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 82,	'Magneton',     '082', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 83,	'Farfetch\'d',  '083', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 84,	'Doduo',        '084', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 85,	'Dodrio',       '085', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 86,	'Seel',         '086', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 87,	'Dewgong',      '087', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 88,	'Grimer',       '088', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 89,	'Muk',          '089', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 90,	'Shellder',     '090', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 91,	'Cloyster',     '091', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 92,	'Gastly',       '092', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 93,	'Haunter',      '093', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 94,	'Gengar',       '094', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 95,	'Onix',         '095', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 96,	'Drowzee',      '096', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 97,	'Hypno',        '097', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 98,	'Krabby',       '098', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES ( 99,	'Kingler',      '099', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (100, 'Voltorb',      '100', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (101, 'Electrode',    '101', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (102,	'Exeggcute',    '102', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (103,	'Exeggutor',    '103', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (104,	'Cubone',       '104', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (105,	'Marowak',      '105', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (106,	'Hitmonlee',    '106', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (107,	'Hitmonchan',   '107', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (108,	'Lickitung',    '108', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (109,	'Koffing',      '109', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (110,	'Weezing',      '110', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (111,	'Rhyhorn',      '111', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (112,	'Rhydon',       '112', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (113,	'Chansey',      '113', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (114,	'Tangela',      '114', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (115,	'Kangaskhan',   '115', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (116,	'Horsea',       '116', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (117,	'Seadra',       '117', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (118,	'Goldeen',      '118', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (119,	'Seaking',      '119', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (120,	'Staryu',       '120', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (121,	'Starmie',      '121', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (122,	'Mr._Mime',     '122', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (123,	'Scyther',      '123', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (124,	'Jynx',         '124', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (125,	'Electabuzz',   '125', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (126,	'Magmar',       '126', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (127,	'Pinsir',       '127', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (128,	'Tauros',       '128', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (129,	'Magikarp',     '129', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (130,	'Gyarados',     '130', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (131,	'Lapras',       '131', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (132,	'Ditto',        '132', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (133,	'Eevee',        '133', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (134,	'Vaporeon',     '134', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (135,	'Jolteon',      '135', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (136,	'Flareon',      '136', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (137,	'Porygon',      '137', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (138,	'Omanyte',      '138', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (139,	'Omastar',      '139', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (140,	'Kabuto',       '140', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (141,	'Kabutops',     '141', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (142,	'Aerodactyl',   '142', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (143,	'Snorlax',      '143', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (144,	'Articuno',     '144', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (145,	'Zapdos',       '145', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (146,	'Moltres',      '146', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (147,	'Dratini',      '147', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (148,	'Dragonair',    '148', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (149,	'Dragonite',    '149', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (150,	'Mewtwo',       '150', 1);
INSERT INTO pokemon (`id`, `nome`, `numero`, `geracao_id`) VALUES (151,	'Mew',          '151', 1);